spring:
  application:
    name: one
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: example eureka url
#      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true