spring:
  application:
    name: apigateway
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  #      defaultZone: http://discovery:8761/eureka
  instance:
    preferIpAddress: true

zuul:
  routes:
     one:
      path: /one/**
      url: http://localhost:8081/greeting/
     two:
      path: /two/**
      url: http://localhost:8082/greeting/
