spring:
  application:
    name: zuul-server
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    foos:
      path: /greeting/**
      url: http://localhost:8081/greeting/
