spring:
  application:
    name: apigateway
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    service_one:
      path: /one
      url: http://localhost:8081/greeting/
    service_two:
      path: /two
      url: http://localhost:8082/greeting/
